services:
  snitch-db:
    build:
      dockerfile: db.Containerfile
    develop:
      watch:
        - action: rebuild
          path: go.mod
        - action: rebuild
          path: pkg
        - action: rebuild
          path: cmd/db
        - action: rebuild
          path: internal/db
        - action: rebuild
          path: internal/shared
    restart: unless-stopped
    image: snitch-db
    environment:
      - DB_DIR_PATH=./data
      - CERT_FILE_PATH=./certs/db/cert.pem
      - KEY_FILE_PATH=./certs/db/key.pem
    ports:
      - 5200:5200
    volumes:
      - ./data:/app/data
      - ./certs:/app/certs:ro

  snitch-backend:
    build:
      dockerfile: backend.Containerfile
    develop:
      watch:
        - action: rebuild
          path: go.mod
        - action: rebuild
          path: pkg
        - action: rebuild
          path: cmd/backend
        - action: rebuild
          path: internal/backend
        - action: rebuild
          path: internal/shared
    restart: unless-stopped
    image: snitch-backend
    depends_on:
      - snitch-db
    environment:
      - CA_CERT_FILE_PATH=./certs/ca/ca-cert.pem
      - CERT_FILE_PATH=./certs/backend/cert.pem
      - KEY_FILE_PATH=./certs/backend/key.pem
      - SNITCH_DB_HOST=snitch-db
      - SNITCH_DB_PORT=5200
    ports:
      - 4200:4200
    volumes:
      - ./certs:/app/certs:ro

  snitch-bot:
    build:
      dockerfile: bot.Containerfile
    develop:
      watch:
        - action: rebuild
          path: go.mod
        - action: rebuild
          path: pkg
        - action: rebuild
          path: cmd/bot
        - action: rebuild
          path: internal/bot
        - action: rebuild
          path: internal/shared
    restart: unless-stopped
    image: snitch-bot
    depends_on:
      - snitch-backend
    environment:
      - CA_CERT_FILE_PATH=./certs/ca/ca-cert.pem
      - SNITCH_DISCORD_TOKEN=${SNITCH_DISCORD_TOKEN}
      - SNITCH_BACKEND_HOST=snitch-backend
      - SNITCH_BACKEND_PORT=4200
    volumes:
      - ./certs:/app/certs:ro
