// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package metadata

import (
	"context"
)

type Querier interface {
	AddServerToGroup(ctx context.Context, arg AddServerToGroupParams) error
	// Metadata database queries (groups and servers)
	CreateGroup(ctx context.Context, arg CreateGroupParams) error
	FindGroupByServer(ctx context.Context, serverID string) (string, error)
	ListServers(ctx context.Context, groupID string) ([]ListServersRow, error)
}

var _ Querier = (*Queries)(nil)
