// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package groupdb

import (
	"context"
)

type Querier interface {
	CreateReport(ctx context.Context, arg CreateReportParams) (int64, error)
	// User history queries
	CreateUserHistory(ctx context.Context, arg CreateUserHistoryParams) (int64, error)
	DeleteReport(ctx context.Context, reportID int64) (int64, error)
	EnsureServerExists(ctx context.Context, serverID string) error
	// Group database queries (reports and users)
	EnsureUserExists(ctx context.Context, userID string) error
	GetReport(ctx context.Context, reportID int64) (Report, error)
	GetUserHistory(ctx context.Context, userID string) ([]UserHistory, error)
	ListReports(ctx context.Context) ([]Report, error)
	ListReportsByUser(ctx context.Context, reportedUserID string) ([]Report, error)
}

var _ Querier = (*Queries)(nil)
