name: Run Go build and tests

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Build Backend
        run: go build ./cmd/backend

      - name: Build Bot
        run: go build ./cmd/bot

      - name: Test
        run: go test -v ./... -json > TestResults.json

      - name: Upload Go test results
        uses: actions/upload-artifact@v4
        with:
          name: GoTestResults
          path: TestResults.json
