name: SQLC Checks

on:
  push:
  pull_request:

jobs:
  sqlc-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup sqlc
        uses: sqlc-dev/setup-sqlc@v4
        with:
          sqlc-version: '1.29.0'

      - name: Verify generated code is up-to-date
        run: sqlc diff

  sqlc-vet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup sqlc
        uses: sqlc-dev/setup-sqlc@v4
        with:
          sqlc-version: '1.29.0'

      - name: Lint SQL queries
        run: sqlc vet